### ISSUE TITLE
Component not found: sonoff

### ISSUE THREAD

**Issue by violgore** [peterbuga/HASS-sonoff-ewelink#105]
I installed again HA from 0, 

with component Sonoff , said me Component not found: sonoff

¿can help me?

Thanks

**Comment by violgore** [comment]
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py",                                                                                         line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py"                                                                                        , line 28, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'
2019-05-02 20:53:34 ERROR (MainThread) [homeassistant.loader] Unable to find com                                                                                        ponent sonoff
2019-05-02 20:53:34 INFO (MainThread) [homeassistant.loader] Loaded notify from                                                                                         homeassistant.components.notify
2019-05-02 20:53:34 INFO (MainThread) [homeassistant.loader] Loaded cloud from h                                                                                        omeassistant.components.cloud
2019-05-02 20:53:34 INFO (MainThread) [homeassistant.loader] Loaded camera from                                                                                         homeassistant.components.camera
2019-05-02 20:53:34 INFO (MainThread) [homeassistant.loader] Loaded script from                                                                                         homeassistant.components.script
2019-05-02 20:53:34 INFO (MainThread) [homeassistant.loader] Loaded weather from                                                                                         homeassistant.components.weather
2019-05-02 20:53:34 ERROR (MainThread) [homeassistant.loader] Error loading cust                                                                                        om_components.sensor. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/loader.py",                                                                                         line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

**Comment by violgore** [comment]
I try reboot pc and HA sometimes

**Comment by peterbuga** [comment]
install missing python module 
```
import websocket
ModuleNotFoundError: No module named 'websocket
```

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by violgore** [comment]
ok., i have been installe , but now on restart, HA not work

Thanks in advanced

**Comment by peterbuga** [comment]
i'm sorry to say this, but it looks to me that you are ignoring basic installation steps and you're not offering enough enough details to work with. 
due to time constrains, this project is not meant to offer support for everyone and all the levels (you might be better off searching help on the dedicated community forum). if this it's not working for you there's always the tasmota flashing alternative.
all the best!
