### ISSUE TITLE
Fails to load in HA 0.94.1 (hassbian)

### ISSUE THREAD

**Issue by ericbf** [peterbuga/HASS-sonoff-ewelink#116]
Just upgrade my HA setup to 0.94.1 and now the Sonoff integration fails to load:

```
Log Details (ERROR)
Mon Jun 10 2019 23:07:13 GMT-0400 (EDT)

Error loading custom_components.sonoff. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 263, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 28, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'
```

Any ideas?

**Comment by gambalaya** [comment]
If you recently upgraded to python 3.7.3 using the hassbian scripts then it will have created a new virtual environment and you will need to re-add the websocket module (with "pip install websocket-client"). On my setup (RPi 2b) that took a very long time (1 hour) when installing one of the sub-modules (gevent) so be patient...

**Comment by ericbf** [comment]
Any special way to run that in the virtual env? Or run from a specific user?

**Comment by gambalaya** [comment]
Assuming you can login interactively to a terminal session as the Pi user, here's the commands to switch to the homeassistant user, activate the virtual environment and then install:

sudo -u homeassistant -H -s
source /srv/homeassistant/bin/activate
pip install websocket-client

**Comment by ericbf** [comment]
Thank you!! I'm new to this virtual environment stuff, so that is a huge help!

**Comment by ericbf** [comment]
That did it. Thanks for the help!

**Comment by gambalaya** [comment]
You're welcome - cheers.
