### ISSUE TITLE
Homeassistant can't restart

### ISSUE THREAD

**Issue by jwguan** [peterbuga/HASS-sonoff-ewelink#130]
Dear Peterbuga,
When I try to restart homeassistant, I get this errors :

Error loading custom_components.sonoff. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 338, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 26, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'

I have the latest version of hassbian，HomeAssistant 0.96.5

System Health
arch	armv7l
dev	false
docker	false
hassio	false
os_name	Linux
python_version	3.7.3
version	0.96.5
virtualenv	true

Thank you

**Comment by peterbuga** [comment]
you need to install the `websocket-client` python module, there are countless threads pointing out how to do this (and even several times in closed issues of this project).
good luck!
