### ISSUE TITLE
0.99.2   don't use

### ISSUE THREAD

**Issue by Trace-star** [peterbuga/HASS-sonoff-ewelink#150]
2019-09-30 11:09:59 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sonoff. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 346, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 28, in <module>
    import websocket
![image](https://user-images.githubusercontent.com/29688398/65847475-48e21b80-e374-11e9-8733-bb7785c69daf.png)
can't python  any date

**Comment by peterbuga** [comment]
install `websocket`, fix in other similar issues

**Comment by difelice** [comment]
What version do you recommend? I getting this errors too now:
```
2019-09-30 13:29:22 DEBUG (Thread-234833) [custom_components.sonoff] websocket msg: {"error":0,"apikey":"cdca5c4a-df3e-49bc-af84-7376fccd4541","config":{"hb":1,"hbInterval":145},"sequence":"15698465626663811"}
2019-09-30 13:29:22 ERROR (Thread-84920) [custom_components.sonoff] websocket error: Connection is already closed.
2019-09-30 13:29:22 DEBUG (Thread-84920) [custom_components.sonoff] websocket closed
2019-09-30 13:29:22 DEBUG (Thread-84920) [custom_components.sonoff] (re)init websocket
2019-09-30 13:29:23 ERROR (Thread-28) [custom_components.sonoff] websocket error: 'NoneType' object has no attribute 'is_ssl'
2019-09-30 13:29:23 DEBUG (Thread-28) [custom_components.sonoff] websocket closed
2019-09-30 13:29:23 DEBUG (Thread-28) [custom_components.sonoff] (re)init websocket
2019-09-30 13:29:23 ERROR (Thread-120917) [custom_components.sonoff] websocket error: 'NoneType' object has no attribute 'is_ssl'
2019-09-30 13:29:23 DEBUG (Thread-120917) [custom_components.sonoff] websocket closed
2019-09-30 13:29:23 DEBUG (Thread-120917) [custom_components.sonoff] (re)init websocket
2019-09-30 13:29:24 ERROR (Thread-52171) [custom_components.sonoff] websocket error: Connection is already closed.
2019-09-30 13:29:24 DEBUG (Thread-52171) [custom_components.sonoff] websocket closed
2019-09-30 13:29:24 DEBUG (Thread-52171) [custom_components.sonoff] (re)init websocket
```

**Comment by Trace-star** [comment]
![image](https://user-images.githubusercontent.com/29688398/65884017-a99c4300-e3ca-11e9-9957-7bcaa730eb9e.png)

**Comment by difelice** [comment]
😱: 
```
$ pip list | grep websocket
websocket               0.2.1
websocket-client        0.54.0
```

**Comment by difelice** [comment]
Every time I restart HA, the `websocket-client` is downgraded to `0.54.0`, not sure why:
```shell
$ pip show websocket-client
Name: websocket-client
Version: 0.54.0
Summary: WebSocket client for Python. hybi13 is supported.
Home-page: https://github.com/websocket-client/websocket-client.git
Author: liris
Author-email: liris.pp@gmail.com
License: BSD
Location: /srv/homeassistant/lib/python3.7/site-packages
Requires: six
Required-by:
```
