### ISSUE TITLE
Integration is broken in 0.98.5

### ISSUE THREAD

**Issue by GuyKh** [peterbuga/HASS-sonoff-ewelink#153]
Getting the following error in the startup:

```
2019-10-02 17:38:51 INFO (MainThread) [homeassistant.setup] Setting up sonoff
2019-10-02 17:38:54 ERROR (MainThread) [homeassistant.setup] Error during setup of component sonoff
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 168, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/sonoff/__init__.py", line 51, in async_setup
    hass.data[DOMAIN] = Sonoff(hass, config)
  File "/config/custom_components/sonoff/__init__.py", line 106, in __init__
    self.do_login()
  File "/config/custom_components/sonoff/__init__.py", line 190, in do_login
    self.update_devices() # to write the devices list
  File "/config/custom_components/sonoff/__init__.py", line 353, in update_devices
    if self.is_grace_period():
  File "/config/custom_components/sonoff/__init__.py", line 320, in is_grace_period
    grace_time_elapsed = self._skipped_login * int(SCAN_INTERVAL.total_seconds())
NameError: name 'SCAN_INTERVAL' is not defined
```

**Comment by GuyKh** [comment]
Seems like fixed with new file
