### ISSUE TITLE
No Entities Added 

### ISSUE THREAD

**Issue by JangoBritt** [peterbuga/HASS-sonoff-ewelink#155]
I'm trying to add this component, and while my connection seems successful, and I can find devices in debug mode, there are no entities added to my hassio.
```

--------------COPY-FROM-HERE--------------

2019-10-03 16:49:32.237 [D] [{"brandName": "Sonoff", "devConfig": {}, "devGroups": [], "name": "OfficeFan", "offlineTime": "2019-09-27T00:15:25.609Z", "online": true, "onlineTime": "2019-09-29T12:32:10.639Z", "params": {"configure": [{"outlet": 0, "startup": "off"}, {"outlet": 1, "startup": "off"}, {"outlet": 2, "startup": "off"}, {"outlet": 3, "startup": "off"}], "fwVersion": "3.1.0", "init": 1, "lock": 0, "pulse": "off", "pulseWidth": 0, "pulses": [{"outlet": 0, "pulse": "off", "width": 1000}, {"outlet": 1, "pulse": "off", "width": 1000}, {"outlet": 2, "pulse": "off", "width": 1000}, {"outlet": 3, "pulse": "off", "width": 1000}], "sledOnline": "on", "switches": [{"outlet": 0, "switch": "on"}, {"outlet": 1, "switch": "off"}, {"outlet": 2, "switch": "off"}, {"outlet": 3, "switch": "off"}], "version": 8}, "productModel": "iFan02", "type": "10", "uiid": 34}]

2019-10-03 16:49:43.220 [D] [{"brandName": "Sonoff", "devConfig": {}, "devGroups": [], "name": "OfficeFan", "offlineTime": "2019-09-27T00:15:25.609Z", "online": true, "onlineTime": "2019-09-29T12:32:10.639Z", "params": {"configure": [{"outlet": 0, "startup": "off"}, {"outlet": 1, "startup": "off"}, {"outlet": 2, "startup": "off"}, {"outlet": 3, "startup": "off"}], "fwVersion": "3.1.0", "init": 1, "lock": 0, "pulse": "off", "pulseWidth": 0, "pulses": [{"outlet": 0, "pulse": "off", "width": 1000}, {"outlet": 1, "pulse": "off", "width": 1000}, {"outlet": 2, "pulse": "off", "width": 1000}, {"outlet": 3, "pulse": "off", "width": 1000}], "sledOnline": "on", "switches": [{"outlet": 0, "switch": "on"}, {"outlet": 1, "switch": "off"}, {"outlet": 2, "switch": "off"}, {"outlet": 3, "switch": "off"}], "version": 8}, "productModel": "iFan02", "type": "10", "uiid": 34}]

2019-10-03 16:49:54.245 [D] [{"brandName": "Sonoff", "devConfig": {}, "devGroups": [], "name": "OfficeFan", "offlineTime": "2019-09-27T00:15:25.609Z", "online": true, "onlineTime": "2019-09-29T12:32:10.639Z", "params": {"configure": [{"outlet": 0, "startup": "off"}, {"outlet": 1, "startup": "off"}, {"outlet": 2, "startup": "off"}, {"outlet": 3, "startup": "off"}], "fwVersion": "3.1.0", "init": 1, "lock": 0, "pulse": "off", "pulseWidth": 0, "pulses": [{"outlet": 0, "pulse": "off", "width": 1000}, {"outlet": 1, "pulse": "off", "width": 1000}, {"outlet": 2, "pulse": "off", "width": 1000}, {"outlet": 3, "pulse": "off", "width": 1000}], "sledOnline": "on", "switches": [{"outlet": 0, "switch": "on"}, {"outlet": 1, "switch": "off"}, {"outlet": 2, "switch": "off"}, {"outlet": 3, "switch": "off"}], "version": 8}, "productModel": "iFan02", "type": "10", "uiid": 34}]

2019-10-03 16:50:05.287 [D] [{"brandName": "Sonoff", "devConfig": {}, "devGroups": [], "name": "OfficeFan", "offlineTime": "2019-09-27T00:15:25.609Z", "online": true, "onlineTime": "2019-09-29T12:32:10.639Z", "params": {"configure": [{"outlet": 0, "startup": "off"}, {"outlet": 1, "startup": "off"}, {"outlet": 2, "startup": "off"}, {"outlet": 3, "startup": "off"}], "fwVersion": "3.1.0", "init": 1, "lock": 0, "pulse": "off", "pulseWidth": 0, "pulses": [{"outlet": 0, "pulse": "off", "width": 1000}, {"outlet": 1, "pulse": "off", "width": 1000}, {"outlet": 2, "pulse": "off", "width": 1000}, {"outlet": 3, "pulse": "off", "width": 1000}], "sledOnline": "on", "switches": [{"outlet": 0, "switch": "on"}, {"outlet": 1, "switch": "off"}, {"outlet": 2, "switch": "off"}, {"outlet": 3, "switch": "off"}], "version": 8}, "productModel": "iFan02", "type": "10", "uiid": 34}]

2019-10-03 16:50:16.202 [D] [{"brandName": "Sonoff", "devConfig": {}, "devGroups": [], "name": "OfficeFan", "offlineTime": "2019-09-27T00:15:25.609Z", "online": true, "onlineTime": "2019-09-29T12:32:10.639Z", "params": {"configure": [{"outlet": 0, "startup": "off"}, {"outlet": 1, "startup": "off"}, {"outlet": 2, "startup": "off"}, {"outlet": 3, "startup": "off"}], "fwVersion": "3.1.0", "init": 1, "lock": 0, "pulse": "off", "pulseWidth": 0, "pulses": [{"outlet": 0, "pulse": "off", "width": 1000}, {"outlet": 1, "pulse": "off", "width": 1000}, {"outlet": 2, "pulse": "off", "width": 1000}, {"outlet": 3, "pulse": "off", "width": 1000}], "sledOnline": "on", "switches": [{"outlet": 0, "switch": "on"}, {"outlet": 1, "switch": "off"}, {"outlet": 2, "switch": "off"}, {"outlet": 3, "switch": "off"}], "version": 8}, "productModel": "iFan02", "type": "10", "uiid": 34}]

2019-10-03 16:50:25.024 [s] {"entity_id": "switch.sonoff_10004bb450_1", "outlet": 0, "state": "on"}

2019-10-03 16:50:25.025 [s] {"entity_id": "switch.sonoff_10004bb450_2", "outlet": 1, "state": "on"}

2019-10-03 16:50:25.026 [s] {"entity_id": "switch.sonoff_10004bb450_3", "outlet": 2, "state": "off"}

2019-10-03 16:50:25.026 [s] {"entity_id": "switch.sonoff_10004bb450_4", "outlet": 3, "state": "off"}

2019-10-03 16:50:25.030 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10004bb450", "params": {"switches": [{"outlet": 0, "switch": "on"}, {"outlet": 1, "switch": "on"}, {"outlet": 2, "switch": "off"}, {"outlet": 3, "switch": "off"}]}, "sequence": "1570117824848", "tempRec": "10004bb450", "ts": 0, "userAgent": "app"}

2019-10-03 16:50:25.321 [s] {"entity_id": "switch.sonoff_10004bb450_1", "outlet": 0, "state": "on"}

2019-10-03 16:50:25.321 [s] {"entity_id": "switch.sonoff_10004bb450_2", "outlet": 1, "state": "on"}

2019-10-03 16:50:25.322 [s] {"entity_id": "switch.sonoff_10004bb450_3", "outlet": 2, "state": "off"}

2019-10-03 16:50:25.323 [s] {"entity_id": "switch.sonoff_10004bb450_4", "outlet": 3, "state": "off"}

2019-10-03 16:50:25.326 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10004bb450", "params": {"switches": [{"outlet": 0, "switch": "on"}, {"outlet": 1, "switch": "on"}, {"outlet": 2, "switch": "off"}, {"outlet": 3, "switch": "off"}]}, "sequence": "1570117825055", "tempRec": "10004bb450", "ts": 0, "userAgent": "app"}

2019-10-03 16:50:27.207 [D] [{"brandName": "Sonoff", "devConfig": {}, "devGroups": [], "name": "OfficeFan", "offlineTime": "2019-09-27T00:15:25.609Z", "online": true, "onlineTime": "2019-09-29T12:32:10.639Z", "params": {"configure": [{"outlet": 0, "startup": "off"}, {"outlet": 1, "startup": "off"}, {"outlet": 2, "startup": "off"}, {"outlet": 3, "startup": "off"}], "fwVersion": "3.1.0", "init": 1, "lock": 0, "pulse": "off", "pulseWidth": 0, "pulses": [{"outlet": 0, "pulse": "off", "width": 1000}, {"outlet": 1, "pulse": "off", "width": 1000}, {"outlet": 2, "pulse": "off", "width": 1000}, {"outlet": 3, "pulse": "off", "width": 1000}], "sledOnline": "on", "switches": [{"outlet": 0, "switch": "on"}, {"outlet": 1, "switch": "on"}, {"outlet": 2, "switch": "off"}, {"outlet": 3, "switch": "off"}], "version": 8}, "productModel": "iFan02", "type": "10", "uiid": 34}]

2019-10-03 16:50:38.205 [D] [{"brandName": "Sonoff", "devConfig": {}, "devGroups": [], "name": "OfficeFan", "offlineTime": "2019-09-27T00:15:25.609Z", "online": true, "onlineTime": "2019-09-29T12:32:10.639Z", "params": {"configure": [{"outlet": 0, "startup": "off"}, {"outlet": 1, "startup": "off"}, {"outlet": 2, "startup": "off"}, {"outlet": 3, "startup": "off"}], "fwVersion": "3.1.0", "init": 1, "lock": 0, "pulse": "off", "pulseWidth": 0, "pulses": [{"outlet": 0, "pulse": "off", "width": 1000}, {"outlet": 1, "pulse": "off", "width": 1000}, {"outlet": 2, "pulse": "off", "width": 1000}, {"outlet": 3, "pulse": "off", "width": 1000}], "sledOnline": "on", "switches": [{"outlet": 0, "switch": "on"}, {"outlet": 1, "switch": "on"}, {"outlet": 2, "switch": "off"}, {"outlet": 3, "switch": "off"}], "version": 8}, "productModel": "iFan02", "type": "10", "uiid": 34}]

2019-10-03 16:50:45.904 [s] {"entity_id": "switch.sonoff_10004bb450_1", "outlet": 0, "state": "on"}

2019-10-03 16:50:45.905 [s] {"entity_id": "switch.sonoff_10004bb450_2", "outlet": 1, "state": "off"}

2019-10-03 16:50:45.905 [s] {"entity_id": "switch.sonoff_10004bb450_3", "outlet": 2, "state": "off"}

2019-10-03 16:50:45.906 [s] {"entity_id": "switch.sonoff_10004bb450_4", "outlet": 3, "state": "off"}

2019-10-03 16:50:45.916 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10004bb450", "params": {"switches": [{"outlet": 0, "switch": "on"}, {"outlet": 1, "switch": "off"}, {"outlet": 2, "switch": "off"}, {"outlet": 3, "switch": "off"}]}, "sequence": "1570117845629", "tempRec": "10004bb450", "ts": 0, "userAgent": "app"}

2019-10-03 16:50:46.005 [s] {"entity_id": "switch.sonoff_10004bb450_1", "outlet": 0, "state": "on"}

2019-10-03 16:50:46.006 [s] {"entity_id": "switch.sonoff_10004bb450_2", "outlet": 1, "state": "off"}

2019-10-03 16:50:46.006 [s] {"entity_id": "switch.sonoff_10004bb450_3", "outlet": 2, "state": "off"}

2019-10-03 16:50:46.007 [s] {"entity_id": "switch.sonoff_10004bb450_4", "outlet": 3, "state": "off"}

2019-10-03 16:50:46.013 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10004bb450", "params": {"switches": [{"outlet": 0, "switch": "on"}, {"outlet": 1, "switch": "off"}, {"outlet": 2, "switch": "off"}, {"outlet": 3, "switch": "off"}]}, "sequence": "1570117845912", "tempRec": "10004bb450", "ts": 0, "userAgent": "app"}

2019-10-03 16:50:49.269 [D] [{"brandName": "Sonoff", "devConfig": {}, "devGroups": [], "name": "OfficeFan", "offlineTime": "2019-09-27T00:15:25.609Z", "online": true, "onlineTime": "2019-09-29T12:32:10.639Z", "params": {"configure": [{"outlet": 0, "startup": "off"}, {"outlet": 1, "startup": "off"}, {"outlet": 2, "startup": "off"}, {"outlet": 3, "startup": "off"}], "fwVersion": "3.1.0", "init": 1, "lock": 0, "pulse": "off", "pulseWidth": 0, "pulses": [{"outlet": 0, "pulse": "off", "width": 1000}, {"outlet": 1, "pulse": "off", "width": 1000}, {"outlet": 2, "pulse": "off", "width": 1000}, {"outlet": 3, "pulse": "off", "width": 1000}], "sledOnline": "on", "switches": [{"outlet": 0, "switch": "on"}, {"outlet": 1, "switch": "off"}, {"outlet": 2, "switch": "off"}, {"outlet": 3, "switch": "off"}], "version": 8}, "productModel": "iFan02", "type": "10", "uiid": 34}]

2019-10-03 16:51:00.277 [D] [{"brandName": "Sonoff", "devConfig": {}, "devGroups": [], "name": "OfficeFan", "offlineTime": "2019-09-27T00:15:25.609Z", "online": true, "onlineTime": "2019-09-29T12:32:10.639Z", "params": {"configure": [{"outlet": 0, "startup": "off"}, {"outlet": 1, "startup": "off"}, {"outlet": 2, "startup": "off"}, {"outlet": 3, "startup": "off"}], "fwVersion": "3.1.0", "init": 1, "lock": 0, "pulse": "off", "pulseWidth": 0, "pulses": [{"outlet": 0, "pulse": "off", "width": 1000}, {"outlet": 1, "pulse": "off", "width": 1000}, {"outlet": 2, "pulse": "off", "width": 1000}, {"outlet": 3, "pulse": "off", "width": 1000}], "sledOnline": "on", "switches": [{"outlet": 0, "switch": "on"}, {"outlet": 1, "switch": "off"}, {"outlet": 2, "switch": "off"}, {"outlet": 3, "switch": "off"}], "version": 8}, "productModel": "iFan02", "type": "10", "uiid": 34}]

---------------END-OF-COPY----------------
```

**Comment by peterbuga** [comment]
have you looked in developer area? what version of HA you have?

**Comment by JangoBritt** [comment]
aah ok.
Home Assistant ver 0.99.3

found an error in the log, but not sure what it means

```

Fri Oct 04 2019 15:55:29 GMT+0100 (BST)

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 408, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 266, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 300, in _async_write_ha_state
    state = self.state
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 554, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/sonoff/switch.py", line 75, in is_on
    self._state = self.get_state()
  File "/config/custom_components/sonoff/__init__.py", line 638, in get_state
    if 'light' in device['light']:
KeyError: 'light'
```

**Comment by peterbuga** [comment]
you have a slight missing-a-few-commits older version of the `master` branch. the error above has been fixed. try with the latest code 👍

**Comment by JangoBritt** [comment]
go figure! thanks!!! that fixed it
