### ISSUE TITLE
At wits end: Websockets

### ISSUE THREAD

**Issue by spitfire1337** [peterbuga/HASS-sonoff-ewelink#157]
I'm new to homeassistant and python but I'm trying to get this working. But I keep getting failed dependencies errors:

`Error loading custom_components.sonoff. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 346, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 28, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'`

I went ahead and installed websocket & websocket-client, rebooted and am still getting this error. I'm not sure what exactly I'm doing wrong here.

Running pip3 show websocket-client returns:
`Name: websocket-client
Version: 0.54.0
Summary: WebSocket client for Python. hybi13 is supported.
Home-page: https://github.com/websocket-client/websocket-client.git
Author: liris
Author-email: liris.pp@gmail.com
License: BSD
Location: /usr/local/lib/python3.7/dist-packages
Requires: six
Required-by:
`

**Comment by peterbuga** [comment]
if you're using hassbian type of HA install you probably didn't installed (or don't have installed) the websocket module of the venv. you need to activate it and then run `pip3 install websocket-client` (re-read the docs)

**Comment by ashrafmn** [comment]
@peterbuga @spitfire1337

these steps worked for me for the same case

sudo systemctl stop home-assistant@homeassistant.service
sudo -u homeassistant -H -s
source /srv/homeassistant/bin/activate
pip3 install websocket-client
exit
sudo systemctl start home-assistant@homeassistant.service

https://community.home-assistant.io/t/websocket-in-hass-io/23332/23

give it a try

**Comment by spitfire1337** [comment]
I managed to get it to work yesterday running an older version of the component, one of the initial websocket versions. 

@ashrafmn I ran through those steps, updated the component from the master repo and looks like that solved my issue. Thanks!
