### ISSUE TITLE
Not working after 0.100 HA update

### ISSUE THREAD

**Issue by Kejszijo** [peterbuga/HASS-sonoff-ewelink#161]
Log Details (ERROR)
Thu Oct 10 2019 21:02:38 GMT+0200 (közép-európai nyári idő)
Error loading custom_components.sonoff. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 346, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 10, in <module>
    from homeassistant.util.async_ import run_coroutine_threadsafe
ImportError: cannot import name 'run_coroutine_threadsafe' from 'homeassistant.util.async_' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/async_.py)

**Comment by FaserF** [comment]
Same goes for me, I have installed the newest update from this github:

`Error loading custom_components.sonoff. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 346, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 10, in <module>
    from homeassistant.util.async_ import run_coroutine_threadsafe
ImportError: cannot import name 'run_coroutine_threadsafe' from 'homeassistant.util.async_' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/async_.py)`

**Comment by FaserF** [comment]
Fixed it for me, you need to put the new __init__.py also to your ha directory in .homeassistant/custom_components/sonoff as the error says:
File "/home/homeassistant/.homeassistant/custom_components/sonoff/init.py", line 10, in

**Comment by Kejszijo** [comment]
I download the latest release, and it's works for me too.

**Comment by Bettinaglio** [comment]
Updated the files in the custom_components/sonoff did solve the loading error in 0.100.1. Thanks
