### ISSUE TITLE
Sonoff Setup Failed

### ISSUE THREAD

**Issue by Coolie1101** [peterbuga/HASS-sonoff-ewelink#173]
**Version:** Latest

**HA LOG**
```
2019-10-26 11:13:22 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sonoff. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 346, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 28, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'
2019-10-26 11:13:28 ERROR (MainThread) [homeassistant.components.homeassistant] Package sonoff setup failed. Component sonoff Integration 'sonoff' not found.
```

**CONFIG**
```
sonoff:
  username: myemail@email.com
  password: myemailpassword
  scan_interval: 60
  grace_period: 600
  api_region: 'us'
  entity_prefix: True
  debug: False
```

**Comment by Percyfloresc** [comment]
need update with https://github.com/peterbuga/HASS-sonoff-ewelink/releases/tag/v0.3.3

**Comment by Coolie1101** [comment]
Is this different from https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master/sonoff?

**Comment by Percyfloresc** [comment]
Is an update for the hassio 0.1. it works.

**Comment by Coolie1101** [comment]
Still giving the same error. `"Component sonoff Integration 'sonoff' not found."`

**Comment by Coolie1101** [comment]
So, I added a "manifest.json" file and no longer get the previous error, but get the following

`Component error: sonoff - No module named 'websocket'`

**Comment by Coolie1101** [comment]
All good, had to manually install websocket and websocket-client.

Thanks for this great share.
