### ISSUE TITLE
Error while setting up sonoff platform for switch

### ISSUE THREAD

**Issue by fiservedpi** [peterbuga/HASS-sonoff-ewelink#239]
Home assistant: 0.109.6
HASS OS: no
SLOW_SETUP_MAX_WAIT
```TypeError: string indices must be integers```
```Logger: homeassistant.components.switch
Source: custom_components/sonoff/__init__.py:516
Integration: Switch (documentation, issues)
First occurred: 6:14:13 AM (1 occurrences)
Last logged: 6:14:13 AM

Error while setting up sonoff platform for switch
Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT) File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for return fut.result() File "/config/custom_components/sonoff/switch.py", line 15, in async_setup_platform outlets_number = hass.data[SONOFF_DOMAIN].get_outlets(device) File "/config/custom_components/sonoff/__init__.py", line 516, in get_outlets if device['uiid'] in uiid_to_name.keys() and \ TypeError: string indices must be integers ```

**Comment by peterbuga** [comment]
@fiservedpi do this https://github.com/peterbuga/HASS-sonoff-ewelink/issues/237#issuecomment-628086842

**Comment by fiservedpi** [comment]
Awesome ty for the quick response sorry for the duplicate

**Comment by fiservedpi** [comment]
thanks seems to be working after applying the async branch

**Comment by peterbuga** [comment]
good 👍

**Comment by fiservedpi** [comment]
Can I just delete the platforms I don't use? I only have one sonoff basic deployed

```Logger: homeassistant.setup
Source: setup.py:249
First occurred: 1:10:44 PM (1 occurrences)
Last logged: 1:10:44 PM

Unable to prepare setup for platform sonoff.light: Platform not found (No module named 'custom_components.sonoff.light').```

**Comment by peterbuga** [comment]
@fiservedpi if you don't have the devices nothing else will be loaded (it's just organized logic), but if you really want less files you can edit this line in `__init.py__` and remove stuff you don't need
`for component in ['switch', 'sensor', 'binary_sensor', 'light', 'fan']:`

**Comment by fiservedpi** [comment]
Ok was just wondering since it's showing up as an error but I'll just leave well enough alone, thanks again

**Comment by fiservedpi** [comment]
Also looks like some changes are coming down the pipe (of course!) 
Home Assistant 0.110.0b1
HASSIO: No
```Logger: homeassistant.components.switch
Source: components/switch/__init__.py:125
Integration: Switch (documentation, issues)
First occurred: 8:59:22 PM (2 occurrences)
Last logged: 8:59:22 PM

SwitchDevice is deprecated, modify SonoffSwitch to extend SwitchEntity
SwitchDevice is deprecated, modify SonoffDebugSwitch to extend SwitchEntity```

**Comment by peterbuga** [comment]
it'll have to wait now...
