### ISSUE TITLE
First setup issues

### ISSUE THREAD

**Issue by cobotkarl** [peterbuga/HASS-sonoff-ewelink#250]
Hi,

I've setup a headless RPi 3B+ with hassio. I am not getting this working... What I've done is the following:

Changes made according to specifications in configuration.yaml aswell as copied the *.py files to .homeassistant/custom_components/sonoff/

First issue log
> Logginformation (ERROR)
> Logger: homeassistant.setup
> Source: setup.py:127
> First occurred: 13:26:17 (8 occurrences)
> Last logged: 13:26:17
> 
> Setup failed for entity_prefix: Integration not found.
> Setup failed for username: Integration not found.
> Setup failed for grace_period: Integration not found.
> Setup failed for sonoff: Integration not found.
> Setup failed for debug: Integration not found.

Second issue log

> Logginformation (ERROR)
> Logger: homeassistant.loader
> Source: custom_components/sonoff/__init__.py:28
> First occurred: 13:26:17 (1 occurrences)
> Last logged: 13:26:17
> 
> Error loading custom_components.sonoff. Make sure all dependencies are installed
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/loader.py", line 436, in _load_file
>     module = importlib.import_module(path)
>   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/homeassistant/.homeassistant/custom_components/sonoff/__init__.py", line 28, in <module>
>     import websocket
> ModuleNotFoundError: No module named 'websocket'

Any ideas?

**Comment by IacopoOrtis** [comment]
If you used virtual environment:
1) enter virtual env
2) `pip3 install websocket-client`
OR
`pip install websocket-client`.

And you should good to go
