### ISSUE TITLE
SonOff not working on 2021.1.4

### ISSUE THREAD

**Issue by jpiedrar** [peterbuga/HASS-sonoff-ewelink#280]
Logger: homeassistant.setup
Source: custom_components/sonoff/__init__.py:178
First occurred: 9:40:05 AM (1 occurrences)
Last logged: 9:40:05 AM

Error during setup of component sonoff
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/sonoff/__init__.py", line 53, in async_setup
    hass.data[DOMAIN] = Sonoff(hass, config)
  File "/config/custom_components/sonoff/__init__.py", line 100, in __init__
    self.do_login()
  File "/config/custom_components/sonoff/__init__.py", line 178, in do_login
    resp = r.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tuncay59** [comment]
Logger: homeassistant.setup
Source: setup.py:138
First occurred: 20:56:11 (1 occurrences)
Last logged: 20:56:11

Setup failed for sonoff: Requirements for sonoff not found: ['uuid'].
