### ISSUE TITLE
Looks like adding device other than Sonoff Basic breaks the whole component

### ISSUE THREAD

**Issue by 2016for** [peterbuga/HASS-sonoff-ewelink#3]
Initially had a single Sonoff Basic, things were working well.
Added a Sonoff 4Ch pro, now don't see even the sonoff basic.

Error in Log:
```
Error while setting up platform sonoff
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/config/custom_components/switch/sonoff.py", line 23, in async_setup_platform
    entity = SonoffSwitch(hass, device)
  File "/config/custom_components/switch/sonoff.py", line 36, in __init__
    SonoffDevice.__init__(self, hass, device)
  File "/config/custom_components/sonoff.py", line 333, in __init__
    self._state         = device['params']['switch'] == 'on'
KeyError: 'switch'
```

**Comment by peterbuga** [comment]
Read my "Credits" section 😆 

Will be fixed but I needed to see the output for myself before l blindly commit and ask for you to test.

**Comment by 2016for** [comment]
Please check other issue, have added the json there.

**Comment by 2016for** [comment]
Some new Progress here. @peterbuga is the man! Should be able to get this working!

**Comment by peterbuga** [comment]
it works now, thanks for debugging assistance @2016for!
closing.
