### ISSUE TITLE
Unable to find component sonoff

### ISSUE THREAD

**Issue by ilgeko** [peterbuga/HASS-sonoff-ewelink#36]
Hi,
I followed the readme, but the component fails to load.
Checking the config in the ui, tells component not found: sonoff.

This is the home-assistant.log:
2019-01-09 22:41:30 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sonoff. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 92, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/sonoff.py", line 26, in <module>
    import websocket
ImportError: No module named 'websocket'
2019-01-09 22:41:30 ERROR (MainThread) [homeassistant.loader] Unable to find component sonoff
2019-01-09 22:41:30 ERROR (MainThread) [homeassistant.setup] Setup failed for sonoff: Component not found.
2019-01-09 22:41:31 ERROR (MainThread) [homeassistant.components.device_tracker] Unable to load /home/homeassistant/.homeassistant/known_devices.yaml: Config file not found: /home/homeassistant/.homeassistant/known_devices.yaml
2019-01-09 22:41:32 ERROR (Thread-8) [homeassistant.components.notify.ios] The notify.ios platform was loaded but no devices exist! Please check the documentation at https://home-assistant.io/ecosystem/ios/notifications/ for more information
2019-01-09 22:57:17 ERROR (Thread-4) [homeassistant.loader] Error loading custom_components.sonoff. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 92, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/sonoff.py", line 26, in <module>
    import websocket
ImportError: No module named 'websocket'
2019-01-09 22:57:17 ERROR (Thread-4) [homeassistant.loader] Unable to find component sonoff

**Comment by peterbuga** [comment]
hi @ilgeko the fix/error message is somehow buried right in the message log above:
`ImportError: No module named 'websocket'` for some reason your HA install failed to automatically add `websocket-client` package specified in the REQUIREMENTS - try to do a couple of system reboots, _might_ fix it

please also provide more details about your type of HA install/types of devices you have + in the same time make sure you have `websocket-client` and/or any other missing packages installed in your system. you can take a look at this issue too https://github.com/peterbuga/HASS-sonoff-ewelink/issues/35 which is somehow similar. 

there are countless already answered questions on how to add/check packages in HA so please do a bit of googleing to find out 😉

**Comment by ilgeko** [comment]
solved. thanks

**Comment by surak** [comment]
I just installed a clean venv with HomeAssistant, and websocket-client is not installed by default. I would add this to the documentation.

**Comment by peterbuga** [comment]
@surak it's not like i'm doing a fresh install everyday, but the installer used to be automatic. i'll take a swing at it and see what happens, it's dumb thing not to work by default - it's the bare bone of HA 😅
