### ISSUE TITLE
'outlet' not defined

### ISSUE THREAD

**Issue by Knoxie** [peterbuga/HASS-sonoff-ewelink#42]
Error while setting up platform sonoff
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/config/custom_components/sensor/sonoff.py", line 33, in async_setup_platform
    entity = SonoffSensor(hass, device, sensor)
  File "/config/custom_components/sensor/sonoff.py", line 43, in __init__
    SonoffDevice.__init__(self, hass, device)
  File "/config/custom_components/sonoff.py", line 509, in __init__
    if outlet is None:
NameError: name 'outlet' is not defined

**Comment by peterbuga** [comment]
hi, i need more details, please follow the steps from here https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master/sonoff-debug

by any chance, did you tried to do some kind of update and maybe you didn't properly copy-paste the files? because the error above is not on par with the current code (it's a bit weird to be frank). anyhow the `sonoff-debug.py` script should clear some of the confusion ;)

**Comment by Knoxie** [comment]
I just copy pasted the files as per instructions.

Tried running the debug and got errors:
```
# python3 sonoff-debug.py -e 'Knoxie89@gmail.com' -p 'GmK986121!' > devices.json
Traceback (most recent call last):
  File "sonoff-debug.py", line 89, in <module>
    do_login()
  File "sonoff-debug.py", line 52, in do_login
    hex_dig = hmac.new(decryptedAppSecret, json.dumps(app_details), digestmod=hashlib.sha256).digest()
  File "/usr/local/lib/python3.6/hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "/usr/local/lib/python3.6/hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'
```

**Comment by Knoxie** [comment]
I just copy pasted the files as per instructions.

Tried running the debug and got errors:

```
# python3 sonoff-debug.py -e 'email -p 'password' > devices.json
Traceback (most recent call last):
  File "sonoff-debug.py", line 89, in <module>
    do_login()
  File "sonoff-debug.py", line 52, in do_login
    hex_dig = hmac.new(decryptedAppSecret, json.dumps(app_details), digestmod=hashlib.sha256).digest()
  File "/usr/local/lib/python3.6/hmac.py", line 144, in new
    return HMAC(key, msg, digestmod)
  File "/usr/local/lib/python3.6/hmac.py", line 42, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'
```

**Comment by peterbuga** [comment]
you are **not** using the latest version of the files! at least the `sonoff-debug.py` file is old, that error was already fixed in `master` branch.
also, the syntax has changed a bit, there's **-u** (for username) instead of **-e** `python3 sonoff-debug.py -u 'email or phone' -p 'password'`

please remove everything related to sonoff, and copy-paste again from `master`. start from scratch ;)!

**Comment by Knoxie** [comment]
Working after using master instead of latest 'release'. 

This is great! Thank you, i'll eventually get around to flashing to tasmoto or w/e but for now this is much easier!

**Comment by ariel-madril** [comment]
i still have this issue despite using master latest commits
