### ISSUE TITLE
Anyone else have issues today?

### ISSUE THREAD

**Issue by ericmiller777** [peterbuga/HASS-sonoff-ewelink#43]
Nothing's working, especially cannot get my switch's to work in ifttt webhook automations. Using hassio getting a bunch of errors, worked fine the last week or so, just stopped last night. Seems if I restart my raspberry pi it works again but after I try to control some switch's with a ifttt webhook they stop working unless I restart my pi, here is the error:

Log Details (ERROR)
Wed Jan 16 2019 22:20:55 GMT-0800 (Pacific Standard Time)

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 277, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sonoff.py", line 461, in turn_off
    self._state = self._hass.data[DOMAIN].switch(False, self._deviceid, self._outlet)
  File "/config/custom_components/sonoff.py", line 341, in switch
    self._ws.send(json.dumps(payload))
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 239, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 264, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 425, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_socket.py", line 109, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

**Comment by peterbuga** [comment]
Might be because of a ewelink servers failure, it happened before. Try to see if the mobile app works or not, if that ain't working (properly) this component won't either.

**Comment by ericmiller777** [comment]
I dunno either it resolved it self or it was because instead of using my "light" set up to control a sonoff switch, I used the actual switch entity ID, anyway just wanna say thank you, I also own a Sonoff RF btw but I have no actual devices detected only a generic RF button/switch which can turn the light on/off.
