### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by stephanerosi** [peterbuga/HASS-sonoff-ewelink#51]
Hello,
I get this error message every minute, but otherwise the plug-in works fine (I use it with sonoff touch and sonoff basic)
What can I do to help debug?

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 232, in async_update_ha_state
    state = self.state
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 426, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/home/homeassistant/.homeassistant/custom_components/switch/sonoff.py", line 48, in is_on
    self._state = self.get_state()
  File "/home/homeassistant/.homeassistant/custom_components/sonoff.py", line 414, in get_state
    return device['params']['switch'] == 'on' if device else False
KeyError: 'switch'

**Comment by peterbuga** [comment]
i have to assume you added/have a Sonoff bulb (or some other new device i haven't come across yet)in which case please update the component with the latest master/websocket branch.

otherwise please run this steps https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master/sonoff-debug and attach the output

**Comment by stephanerosi** [comment]
I have a Sonoff B1
I'm on latest master branch
Here is attached the debug output

**Comment by peterbuga** [comment]
I took a better look at the 1st post with the error and I can tell 100% that you are not using the latest code! please remove all the `sonoff.py` and use the latest code from `master`, `websocket` or even [v0.3.1](https://github.com/peterbuga/HASS-sonoff-ewelink/releases/tag/v0.3.1) and your problem should be fixed 😉

**Comment by stephanerosi** [comment]
You're right, sorry.
Btw I've switched on branch sonoff-bulb and my B1 works fine with it (v2.6.0)
