### ISSUE TITLE
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)

### ISSUE THREAD

**Issue by marksev1** [peterbuga/HASS-sonoff-ewelink#53]
Hey peterbuga, this is marksev1 from HASS community... I added the lines you told me and now I get the following error:

2019-02-02 10:55:15 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/home/msev/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 287, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/msev/.homeassistant/custom_components/switch/sonoff.py", line 53, in turn_on
    self._state = self._hass.data[SONOFF_DOMAIN].switch(True, self._deviceid, self._outlet)
  File "/home/msev/.homeassistant/custom_components/sonoff.py", line 290, in switch
    self._ws = self._get_ws()
  File "/home/msev/.homeassistant/custom_components/sonoff.py", line 255, in _get_ws
    self._ws = create_connection(('wss://{}:8080/api/ws'.format(self._wshost)), timeout=10)
  File "/home/msev/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 511, in create_connection
    websock.connect(url, **options)
  File "/home/msev/homeassistant/lib/python3.7/site-packages/websocket/_core.py", line 220, in connect
    options.pop('socket', None))
  File "/home/msev/homeassistant/lib/python3.7/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/home/msev/homeassistant/lib/python3.7/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/home/msev/homeassistant/lib/python3.7/site-packages/websocket/_http.py", line 232, in _wrap_sni_socket
    server_hostname=hostname,
  File "/usr/local/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/local/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1056)

**Comment by peterbuga** [comment]
I really don't know what to say/fix :| unless you provide a way for me to (hopefully quickly) replicate the problem I'm afraid there's not much I can do. 
Following these errors it's like going down to rabbit's hole: they might never stop. There might be a conflict with some previous installed packages that are not related to HA, might be better (if possible) to do a fresh install and start from scratch.
Sorry.

**Comment by peterbuga** [comment]
I could probably do it but this implies time for me to invest time to test and debug a single instance of an error not to mention creating a security issue (if i ever want to push this into base HA source, this thing will get it rejected). 
Will all due respect I think it's better for you to fix the certificates problem that might affect other parts of your system too. 
I'm sorry but I won't fix it!
