### ISSUE TITLE
Cannot establish a new connection

### ISSUE THREAD

**Issue by Tony763** [peterbuga/HASS-sonoff-ewelink#59]
Hello, I have a problem with sonoff component.
Component stopped working for me. Tried few restarts, downloaded latest version but result is same. Sonoff cannot establish a new connection when starting.

```
sonoff:
  username: xxxxx@gmail.com
  password: xxxxxxx
  scan_interval: 60
  grace_period: 600
  api_region: 'eu'
  entity_name: true
```
```
Wed Feb 20 2019 19:41:58 GMT+0100 (Středoevropský standardní čas)
Error during setup of component sonoff
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f8f4e6ee588>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='eu-disp.coolkit.cc', port=8080): Max retries exceeded with url: /dispatch/app (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8f4e6ee588>: Failed to establish a new connection: [Errno -3] Try again',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/sonoff.py", line 52, in async_setup
    hass.data[DOMAIN] = Sonoff(config)
  File "/config/custom_components/sonoff.py", line 96, in __init__
    self.do_login()
  File "/config/custom_components/sonoff.py", line 168, in do_login
    self.set_wshost()
  File "/config/custom_components/sonoff.py", line 173, in set_wshost
    r = requests.post('https://%s-disp.coolkit.cc:8080/dispatch/app' % self._api_region, headers=self._headers)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='eu-disp.coolkit.cc', port=8080): Max retries exceeded with url: /dispatch/app (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8f4e6ee588>: Failed to establish a new connection: [Errno -3] Try again',))
```

Ping from Hassio (inside docker) is ok.
```
ping eu-disp.coolkit.cc
PING eu-disp.coolkit.cc (52.28.157.61): 56 data bytes
64 bytes from 52.28.157.61: seq=0 ttl=46 time=23.010 ms
64 bytes from 52.28.157.61: seq=1 ttl=46 time=24.189 ms
```

Enviroment:
```
arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.6.6
timezone | Europe/Prague
version | 0.87.1
virtualenv | false
```

**Comment by peterbuga** [comment]
can you try this https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master/sonoff-debug from hassion (and/or other machine linux/osx/vm if possible)? it's the same code as the component but can give a small debug information. ps: pinging a server doesn't mean you can actually properly connect to it too

**Comment by Tony763** [comment]
After a night it started to work again. Sorry for issue

**Comment by peterbuga** [comment]
Praise the Lord! It's a miracle! 🙌 😄

**Comment by Tony763** [comment]
Miracle not happened. Today I updated HA to 0.88 and after reboot issue is back. When I run sonoff-debug.py from Ubuntu it's OK and actually get information's but from Hassio it throw error.
I tried it with a main account and with shared. Both do same.

```
sonoff-debug python3 sonoff-debug.py xxx@xxxx.com xxxxxxxx > hassio.json
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fb231cf9978>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='us-api.coolkit.cc', port=8080): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb231cf9978>: Failed to establish a new connection: [Errno -3] Try again',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sonoff-debug.py", line 100, in <module>
    do_login()
  File "sonoff-debug.py", line 67, in do_login
    r = requests.post('https://%s-api.coolkit.cc:8080/api/user/login' % api_region, headers=headers, json=app_details)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us-api.coolkit.cc', port=8080): Max retries exceeded with url: /api/user/login (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fb231cf9978>: Failed to establish a new connection: [Errno -3] Try again',))
```
[ubuntu.json.txt](https://github.com/peterbuga/HASS-sonoff-ewelink/files/2895893/ubuntu.json.txt)

**Comment by peterbuga** [comment]
don't you find a bit suspect that exactly the same code works in ubuntu, but not from hassio? i tend to believe that there might be some configuration on your side blocking the requests. do you have any type of firewall/pihole or something similar in place ?
unfortunately i'm not familiar with hassio, never installed it and probably never will therefore i cannot help you too much debugging this.

**Comment by Tony763** [comment]
I have standard IP firewall. I found I left `entity_name` in config. I removed it and I have no occurrence.  It's definitely odd.
