### ISSUE TITLE
Broken Pipe errors / Bad write retry errors

### ISSUE THREAD

**Issue by 2016for** [peterbuga/HASS-sonoff-ewelink#6]
Keep getting some of these here and there:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/service.py", line 277, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sonoff.py", line 420, in turn_on
    self._state = self._hass.data[DOMAIN].switch(True, self._deviceid, self._outlet)
  File "/config/custom_components/sonoff.py", line 322, in switch
    self._ws.send(json.dumps(payload))
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 239, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 264, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 425, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.6/site-packages/websocket/_socket.py", line 112, in send
    return sock.send(data)
  File "/usr/local/lib/python3.6/ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "/usr/local/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
ssl.SSLError: [SSL: BAD_WRITE_RETRY] bad write retry (_ssl.c:2138)
```

**Comment by peterbuga** [comment]
this is a weird low level python or ssl error, a bit out of the scope of this project. i'll try to fix it by catching it and internally retrying the request a few times, more than this i have no idea how to reproduce it :/ 

if possible try to look out for more variables that might trigger this error, like: are you switching on and off fast-ish the switches (one or more of them) ? does HA has a constant and good connection to the internet ?

**Comment by peterbuga** [comment]
just triggered something similar on my side too. it's possible that websocket token (the one that updates the switch states) might expire after 3-6 hours, don't know for sure yet. 

it'll help if you could test it on your side too: restart HA to obtain new login token for sonoff component then try to flip any switch every 1 hour

**Comment by 2016for** [comment]
Haven't restarted HA for a while (maybe a day or so), still working properly.

I think that error was triggered with fast switching of states / or by turning off a light group with multiple switches

**Comment by 2016for** [comment]
Don't think I am getting these any more with the new commits.
