### ISSUE TITLE
HA 0.88.1 on Termux do not work 

### ISSUE THREAD

**Issue by Antarctic74** [peterbuga/HASS-sonoff-ewelink#66]
I have installed HA 0.88.1 on tvbox using Termux.
When I launch HASS I got these errors
`2019-03-02 21:56:09 INFO (MainThread) [homeassistant.setup] Setting up updater
2019-03-02 21:56:09 INFO (MainThread) [homeassistant.setup] Setting up sonoff
2019-03-02 21:56:10 ERROR (MainThread) [homeassistant.setup] Error during setup of component sonoff
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/homeassistant/setup.py", line 151, in _async_setup_component
    hass, processed_config)
  File "/data/data/com.termux/files/home/.homeassistant/custom_components/sonoff/__init__.py", line 52, in async_setup
    hass.data[DOMAIN] = Sonoff(config)
  File "/data/data/com.termux/files/home/.homeassistant/custom_components/sonoff/__init__.py", line 96, in __init__
    self.do_login()
  File "/data/data/com.termux/files/home/.homeassistant/custom_components/sonoff/__init__.py", line 162, in do_login
    self._bearer_token  = resp['at']
KeyError: 'at'
2019-03-02 21:56:10 INFO (MainThread) [homeassistant.setup] Setting up sun
2019-03-02 21:56:10 INFO (MainThread) [homeassistant.setup] Setup of domain sun took 0.1 seconds.`

Anyone know what is wrong?

**Comment by peterbuga** [comment]
double check if you typed the user/email & password ok, it's very important to be `'` between single quotes `'` 
also try to the instructions from [here](https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master/sonoff-debug) and let me know if you get any output. 
another common problem might be that HA install is behind a firewall or proxy, so please double check on that too.

**Comment by Antarctic74** [comment]
Sorry mate I am a lamer, lol, wrong password..

**Comment by peterbuga** [comment]
:stuck_out_tongue_winking_eye:

**Comment by mclaudiopt** [comment]
hello
i have tried to setup with following:

sonoff:
  username: '+351xxx'
  password: 'xxxxx'
but when i test configuration in hassio, it keep waiting and waiting and no output (if configuration is correct or not is given. what can be wrong?
thanks
