### ISSUE TITLE
sonoff sc

### ISSUE THREAD

**Issue by ashrafmn** [peterbuga/HASS-sonoff-ewelink#74]
hi,,
will be great if we can add support to sonoff sc.
I will upload the debug file as soon as i'm able to run it.

thanks for your support on getting this done.

**Comment by ashrafmn** [comment]
i got the below error running the debug.

pi@hassbian:/home/homeassistant/.homeassistant/custom_components/sonoff-debug $ sudo python sonoff-debug.py  --username 'ashraf.mn@outlook.com' --password  'anadeem232' > /home/pi/devices.json
Traceback (most recent call last):
  File "sonoff-debug.py", line 2, in <module>
    import argparse, sys, json, time, random, pprint, base64, requests, hmac, hashlib, re
ImportError: No module named requests

would you plz help

**Comment by ashrafmn** [comment]
Hi,
i got the below error while running the debug


pi@hassbian:/home/homeassistant/.homeassistant/custom_components/sonoff-debug $ sudo python sonoff-debug.py  --username 'xxxxxxxxx' --password  'xxxxxxx' > /home/pi/devices.json
Traceback (most recent call last):
  File "sonoff-debug.py", line 2, in <module>
    import argparse, sys, json, time, random, pprint, base64, requests, hmac, hashlib, re
ImportError: No module named requests

**Comment by peterbuga** [comment]
@ashrafmn take a look at this comment (and the others around it) https://github.com/peterbuga/HASS-sonoff-ewelink/issues/35#issuecomment-452749386 it's the same problem

**Comment by ashrafmn** [comment]
followed all the suggested steps, i also tried it from another mac pc, getting exactly the same error :(

**Comment by peterbuga** [comment]
@ashrafmn i hope not to offence too much but i sort of got tired to explain this basic problem over and over so i took the time and added (i hope) a super basic way to provide me the information requested above. 
i've redone a bit chunk of the component and now it's enough **just to install the component** and literally flip a switch, is this easy enough?
please update the component with the last files from [master branch](https://github.com/peterbuga/HASS-sonoff-ewelink) and **read 10 times** the new installation option + the `debug` section

i really don't know how i can make it more easier than this, if you still can't figure it out... just wait and maybe someone else with a similar device will be able to provide the output i need.

**Comment by ashrafmn** [comment]
Hi Pet,

will this log capture help?

2019-08-13 13:30:45.236 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 32}, "ts": 0, "userAgent": "device"}

2019-08-13 13:30:51.132 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 3, "temperature": 32}, "ts": 0, "userAgent": "device"}

2019-08-13 13:31:12.857 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "1000413b32", "params": {"state": "on"}, "sequence": "1565692272523", "tempRec": "1000413b32", "ts": 0, "userAgent": "app"}

2019-08-13 13:31:19.738 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 32}, "ts": 0, "userAgent": "device"}

2019-08-13 13:31:23.781 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "1000516faf", "params": {"state": "on"}, "sequence": "1565692281548", "tempRec": "1000516faf", "ts": 0, "userAgent": "app"}

2019-08-13 13:31:26.169 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 3, "temperature": 32}, "ts": 0, "userAgent": "device"}

2019-08-13 13:31:29.257 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 32}, "ts": 0, "userAgent": "device"}

2019-08-13 13:31:32.087 [s] {"entity_id": "switch.sonoff_1000262454", "outlet": null, "state": "on"}

2019-08-13 13:31:32.088 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "1000262454", "from": "device", "params": {"switch": "on"}, "seq": "40", "sequence": "1565692291752", "ts": 0, "userAgent": "device"}

2019-08-13 13:31:34.661 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 3, "temperature": 32}, "ts": 0, "userAgent": "device"}

2019-08-13 13:31:39.529 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 32}, "ts": 0, "userAgent": "device"}

2019-08-13 13:31:41.335 [s] {"entity_id": "switch.sonoff_1000262454", "outlet": null, "state": "off"}

2019-08-13 13:31:41.336 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "1000262454", "from": "device", "params": {"switch": "off"}, "seq": "41", "sequence": "1565692301105", "ts": 0, "userAgent": "device"}

2019-08-13 13:31:42.173 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 3, "temperature": 32}, "ts": 0, "userAgent": "device"}

2019-08-13 13:31:50.293 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "1000413b32", "params": {"state": "off"}, "sequence": "1565692309969", "tempRec": "1000413b32", "ts": 0, "userAgent": "app"}

2019-08-13 13:31:55.241 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 32}, "ts": 0, "userAgent": "device"}

2019-08-13 13:31:58.185 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "1000516faf", "params": {"state": "off"}, "sequence": "1565692316139", "tempRec": "1000516faf", "ts": 0, "userAgent": "app"}

2019-08-13 13:32:03.370 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 3, "temperature": 32}, "ts": 0, "userAgent": "device"}

**Comment by ashrafmn** [comment]
Hi @peterbuga 

will the above logs be enough for now to look into the sonoff SC?

Regards,

**Comment by peterbuga** [comment]
yes and no-ish,
this is an important piece of information but because i've never got the the dump of a sonoff-sc i can only guess the overall structure and what information it's available.

by any chance could you please give it another try to run the `sonoff-debug.py` script?

**Comment by ashrafmn** [comment]
hi @peterbuga 

here u go another capture,, hope this will help

. --------------COPY-FROM-HERE--------------

2019-08-29 20:37:48.472 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 26}, "ts": 0, "userAgent": "device"}

2019-08-29 20:38:10.441 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 60, "light": 10, "noise": 5, "temperature": 26}, "ts": 0, "userAgent": "device"}

2019-08-29 20:38:15.505 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 60, "light": 10, "noise": 4, "temperature": 26}, "ts": 0, "userAgent": "device"}

2019-08-29 20:38:45.535 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 60, "light": 10, "noise": 5, "temperature": 26}, "ts": 0, "userAgent": "device"}

2019-08-29 20:38:55.748 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 60, "light": 10, "noise": 4, "temperature": 26}, "ts": 0, "userAgent": "device"}

2019-08-29 20:39:43.524 [W] {"action": "sysmsg", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "1000413b32", "params": {"online": true}, "ts": 0}

2019-08-29 20:39:43.863 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "1000413b32", "from": "device", "params": {"channel0": "211", "channel1": "211", "channel2": "0", "channel3": "0", "channel4": "0", "fwVersion": "2.6.0", "rssi": -75, "staMac": "xx:xx:xx:xx:xx:xx", "state": "off"}, "ts": 0, "userAgent": "device"}

2019-08-29 20:40:36.908 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "100067ae87", "from": "device", "params": {"rssi": -70}, "ts": 0, "userAgent": "device"}

2019-08-29 20:41:36.974 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "100067ae87", "from": "device", "params": {"rssi": -67}, "ts": 0, "userAgent": "device"}

2019-08-29 20:43:26.555 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 5, "temperature": 26}, "ts": 0, "userAgent": "device"}

2019-08-29 20:43:32.184 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 26}, "ts": 0, "userAgent": "device"}

2019-08-29 20:44:01.513 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 27}, "ts": 0, "userAgent": "device"}

2019-08-29 20:44:05.539 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 26}, "ts": 0, "userAgent": "device"}

2019-08-29 20:44:23.513 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 27}, "ts": 0, "userAgent": "device"}

2019-08-29 20:44:55.268 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 26}, "ts": 0, "userAgent": "device"}

2019-08-29 20:45:03.515 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 27}, "ts": 0, "userAgent": "device"}

2019-08-29 20:51:05.615 [W] {"action": "sysmsg", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "1000516faf", "params": {"online": false}, "ts": 0}

2019-08-29 20:51:12.813 [W] {"action": "sysmsg", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "1000516faf", "params": {"online": true}, "ts": 0}

2019-08-29 20:51:13.194 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "1000516faf", "from": "device", "params": {"channel0": "192", "channel1": "192", "channel2": "0", "channel3": "0", "channel4": "0", "fwVersion": "2.6.0", "rssi": -70, "staMac": "xx:xx:xx:xx:xx:xx", "state": "off"}, "ts": 0, "userAgent": "device"}

2019-08-29 20:51:35.900 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 28}, "ts": 0, "userAgent": "device"}

2019-08-29 20:51:45.507 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 27}, "ts": 0, "userAgent": "device"}

2019-08-29 20:52:05.985 [W] {"action": "update", "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", "deviceid": "10003b72dc", "from": "device", "params": {"dusty": 2, "humidity": 59, "light": 10, "noise": 4, "temperature": 28}, "ts": 0, "userAgent": "device"}

---------------END-OF-COPY----------------

**Comment by peterbuga** [comment]
sorry if i mislead you above :( actually i mean this script dump https://github.com/peterbuga/HASS-sonoff-ewelink/issues/74#issuecomment-480389665 or this https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master/sonoff-debug

if you still can't get it to work, i'll probably include/dump it automatically as a starter for the dumps you've done above. just to be clear, the above info is really good and i'll try to work with it even if i don't have the complete picture

**Comment by ashrafmn** [comment]
@peterbuga here u go,,
hope it will help,, I'm really excited to get this available in home assistant to use the temp as a trigger and to use the iOS notification if temp reaches a specific number


  {
    "__v": 0,
    "_id": "[hidden]",
    "apikey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "brandLogoUrl": "https://as-ota.coolkit.cc/logo/KRZ54OifuGmjoEMxT1YYM3Ybu2fj5K2C.png",
    "brandName": "Sonoff",
    "createdAt": "xxxx-xx-xxxxx:xx:xx.xxx",
    "devConfig": {},
    "devGroups": [],
    "deviceStatus": "0",
    "deviceUrl": "https://as-api.coolkit.cc:8080/api/detail/5a2e1b3a0cf772f92c342f02_en.html",
    "deviceid": "[hidden]",
    "devicekey": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    "extra": {
      "_id": "[hidden]",
      "extra": {
        "apmac": "xx:xx:xx:xx:xx:xx",
        "brandId": "58e5f344baeb368720e25469",
        "description": "WWJG001294",
        "mac": "xx:xx:xx:xx:xx:xx",
        "manufacturer": "\u6df1\u5733\u677e\u8bfa\u6280\u672f\u6709\u9650\u516c\u53f8",
        "model": "PSA-BTA-GL",
        "modelInfo": "5a2e1b3a0cf772f92c342f02",
        "staMac": "xx:xx:xx:xx:xx:xx",
        "ui": "\u4f20\u611f\u5668\u4e2d\u5fc3",
        "uiid": 18
      }
    },
    "group": "",
    "groups": [],
    "ip": "[hidden]",
    "location": "",
    "name": "[hidden]",,
    "offlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "online": true,
    "onlineTime": "xxxx-xx-xxxxx:xx:xx.xxx",
    "params": {
      "bindInfos": {
        "gaction": [
          "f4846e50-0071-4fe3-9437-41c26c8b147f_ewelink-google-home-v1"
        ]
      },
      "dusty": 2,
      "fwVersion": "2.7.0",
      "humidity": 57,
      "light": 10,
      "noise": 4,
      "rssi": -24,
      "sledOnline": "on",
      "staMac": "xx:xx:xx:xx:xx:xx",
      "temperature": 26
    },
    "productModel": "SC",
    "settings": {
      "alarmNotify": 1,
      "opsHistory": 1,
      "opsNotify": 0
    },
    "sharedBy": {
      "nickname": "nickname",
      "permit": 15,
      "phoneNumber": "[hidden]",,
      "shareTime": 1553335326424
    },
    "showBrand": true,
    "type": "10",
    "uiid": 18
  },

**Comment by peterbuga** [comment]
@ashrafmn thanks for the output 🙌!
and good news: now that i have all the information i need it turns out it's actually terrible easy to add it (just a few lines), i'll push it in a few days 👍

**Comment by ashrafmn** [comment]
@peterbuga great news ,, and thanks a lot for your support and help on this.

will be looking forward once this is release.
please do let me know once its released.

Regards,
Ashraf

**Comment by ashrafmn** [comment]
hi @peterbuga 
any chance??

**Comment by peterbuga** [comment]
@ashrafmn give it a try https://github.com/peterbuga/HASS-sonoff-ewelink/commit/d5623863421ba383ab7abf8c4badcfd15698a717 

ps: the values will update to a minimum value of 60sec (aka the value of `scan_interval `). i sort of believe you might not need something faster than that (in next version version i might made them update instantly like the switches... that if it's not plagued by fw 3.3.0+ bug that's killing sensors on POW R2 devices, IMO better to not update it if it works ok now!)

**Comment by ashrafmn** [comment]
@peterbuga the sonoff SC sensors are not yet discovered by the custom_componant 
i still don't see the 5 sensors (light, temp, humid, noise and air quality)

**Comment by peterbuga** [comment]
@ashrafmn could you please give it another go 😊? @difelice pointed and pushed a fix for a small typo i've made that for sure was messing stuff up, most likely throwing some error too

**Comment by peterbuga** [comment]
@ashrafmn you should see something like this (i used your dump from above to inject the information like I would have the device in my eWeLink account, it should definitely work now)
<img width="798" alt="Screen Shot 2019-09-29 at 11 23 11" src="https://user-images.githubusercontent.com/6365174/65830021-ede4f180-e2ab-11e9-9285-68eeb04ec886.png">

**Comment by ashrafmn** [comment]
Thanks @peterbuga

How do I get the updated code to try?
Is it in the master  or websocket branch?

**Comment by peterbuga** [comment]
@ashrafmn `master`
that if, hopefully you don't get hit by the bug it's going around these days with the latest version of HA (so you might wanna hold on a bit longer on upgrading it)

**Comment by ashrafmn** [comment]
@peterbuga you are the king  :)
my sonoff sc sensors are available running HA 9.33 on hassbian pi

you may close issue #74
