### ISSUE TITLE
Unknown module error while loading component

### ISSUE THREAD

**Issue by mooonsee** [peterbuga/HASS-sonoff-ewelink#76]
During loading process HA throw exception for switch and sensor:

2019-03-25 23:41:01 WARNING (MainThread) [homeassistant.loader] You are using a custom component for sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2019-03-25 23:41:04 ERROR (MainThread) [homeassistant.components.device_tracker] Unable to load /config/known_devices.yaml: Config file not found: /config/known_devices.yaml
2019-03-25 23:41:04 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.sonoff.switch. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.sonoff.switch'; 'custom_components.sonoff' is not a package

Is there any additional step needed to start this component?
I use HASSIO docker version in latest version on Ubuntu 18.10.

Regards,
Szymon

**Comment by peterbuga** [comment]
@mooonsee remove all the files/folders related to sonoff component in `custom_components` and re-upload a new version of the files

**Comment by mooonsee** [comment]
Hi Peterbuga,

I have latest .py scripts taken from github yesterday (there are no new changes until that time).
I've created custom_components folder specially for sonoff component, so there are no more thinks inside.

**Comment by peterbuga** [comment]
@mooonsee if your HASSIO version is greater than 0.88 you must use the version [master-HA0.88+](https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master-HA0.88+) or [websocket-HA0.88+](https://github.com/peterbuga/HASS-sonoff-ewelink/tree/websocket-HA0.88+)

if you didn't already, repeat the steps mentioned above!

**Comment by peterbuga** [comment]
@mooonsee do you have any updates? i would like to close this issue if it's fixed, thanks
