### ISSUE TITLE
System health warnings in hass.io

### ISSUE THREAD

**Issue by dwl99** [peterbuga/HASS-sonoff-ewelink#81]
Hass.io system health log reporting:
`Integrations need to be in their own folder. Change switch/sonoff.py to sonoff/switch.py. This will stop working soon.`
`Integrations need to be in their own folder. Change sensor/sonoff.py to sonoff/sensor.py. This will stop working soon.`
```
Error loading custom_components.sonoff.switch. Make sure all dependencies are installed

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.sonoff.switch'; 'custom_components.sonoff' is not a package
```

**Comment by peterbuga** [comment]
use branch [master-HA0.88+](https://github.com/peterbuga/HASS-sonoff-ewelink/tree/master-HA0.88+) or [websocket-HA0.88+](https://github.com/peterbuga/HASS-sonoff-ewelink/tree/websocket-HA0.88+)
